server:
  port: 8080
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3311/sandbox?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
notificador:
  email:
    host-servidor: smtp.local.likwi.com.br
    host-porta: 25

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
